config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'userlist', to: 'users#userlist'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :destroy, :update, :editd]do
    member do
      get :followings
      get :followers
      get :likes
    end
    collection do
      get :search
    end
  end
  post '/books/:id/edit', to: 'users#edit'
  resources :books
  resources :relationships, only: [:create, :destroy]
   resources :favorites, only: [:create, :destory]
  delete 'favorites', to: 'favorites#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  def self.search(search)
      if search.blank?
        Book.all
      else
        Book.where(['content LIKE ?', "%#{search}%"])
      end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow,class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :books
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :favorites
    has_many :darling, through: :favorites, source: :book
    has_many :reverses_of_ravorite, class_name: 'Favorite', foreign_key: 'book_id'
    has_many :favorited, through: :reverses_of_favorite, source: :user
    
    def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
    end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def favorite(book)
    self.favorites.find_or_create_by(book_id: book.id)
  end

  def unfavorite(book)
    favorite = self.favorites.find_by(book_id: book.id)
    favorite.destroy if favorite
  end
  
  def favorited?(book)
    self.darling.include?(book)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private

    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
        @count_microposts = user.books.count
        @count_followings = user.followings.count
        @count_followers = user.followers.count
        @count_favarites = user.darling.count
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :destroy, :update]
  
  def index
    search
    @user = current_user
    counts(@user)
  end

  def show
    @user = current_user
    
  end

  def new
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:book_id])
    @user = User.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book = current_user.books.build(book_params)
      if @book.save
        flash[:success] = '感想を投稿しました。'
      redirect_to books_url
      else
       @microposts = current_user.microposts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '感想の投稿に失敗しました。'
      render 'toppages/index'
      end
  end


  def update
      @user = current_user
      if @book.update(book_params)
       redirect_to @book
      else
        
      end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :author, :content, :user_id, :image)
    end
    
    def search
      @books = Book.search(params[:search]).order(id: :desc).paginate(page: params[:page], per_page: 4)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 def create
    book = Book.find(params[:book_id])
    @favorite = current_user.favorite(book)
    if @favorite.save
      flash[:success] = 'お気に入りに追加しました。'
      redirect_back(fallback_location: root_path)
    else
      @book = current_user.books.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'お気に入りの追加に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    book = Book.find(params[:book_id])
    @favorite = current_user.unfavorite(book)
    flash[:success] = 'お気に入りを削除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to '/books'
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to '/books'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
     session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @books = Book.order(id: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
  def index
    @user = current_user
    @users = User.order(id: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id]).order(id: :desc).paginate(page: params[:page], per_page: 4)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
   def destroy
    @book = Book.find_by(id: params[:book_id])
    @book.destroy
    @user = User.find(params[:id])
    redirect_to @user
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user= User.find(params[:id])
    @favorited = @user.darling.page(params[:page])
    counts(@user)
  end
  
  def userlist
    @user = User.all
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <aside class="col-sm-4">
   <div class="field">
    <%= form.label :"画像" %>
    <%= form.file_field :image %>
  </div>
  </aside>
  <aside class="col-sm-8">
  <img class="mr-2 rounded" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
  <%= @user.name %>
  
  <div class="field">
    <%= form.label :"タイトル:" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :"著者:" %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :"感想"  %>
    <%= form.text_area :content ,size: "10x5", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </aside>
</div>
<% end %>

app/views/books/edit.html.erb
<%= render 'users/navtab',users: @user %>
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'users/navtab' ,users: @user%>
    <p>キーワード検索</p>
  <%= form_tag(books_path, :method => 'get' ) do %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search', :name => nil %>
  <% end %>
  <br>

    <% @books.each do |book| %>
      <% image = book.image %>
      <% if image.blank? %>
        <% image = "/assets/book2.jpg" %>
      <% end %>
        <img src=<%=image%> align="left">
        <span class="boxcontiner">
        <img class="mr-2 rounded" src="<%= gravatar_url(book.user, { size: 50 }) %>" alt="">
        <%= book.user.name %>
        <br>
         <%= render 'relationships/follow_button', user: book.user %>
         </span>
         <br>
        タイトル：<%= book.name %>
        <br>
        著者:<%= book.author %>
        <br>
        感想
        <br>
        <textarea name="kanso" rows="2" cols="40" readonly><%= book.content %></textarea>
        <br>
        <%= render "favorites/favorite_button" ,book: book %>
        <br clear="left">
        <br>
    <% end %>
   <%= paginate @books %>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'users/navtab', users: @user %>
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @book.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @book.image.url if @book.image? %>
</p>

app/views/favorites/_favorite.html.erb
  <ul class="list-unstyled">
    <% favorited.each do |favorite| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(favorite.user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= link_to favorite.user.name, user_path(favorite.user) %> <span class="text-muted">posted at <%= favorite.created_at %></span>
          </div>
          <div>
            <p class="mb-0"><%= favorite.content %></p>
          </div>
          <div>
          <%= render "favorites/favorite_button" ,book: favorite %>
        </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate favorited %>

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorited?(book) %>
    <%= link_to "Unfavorite", favorites_path(book_id: book.id),method: :delete, class: 'btn btn-info btn-sm' %>
 <% else %>
    <%= link_to "Favorite", favorites_path(book_id: book.id),method: :create, class: 'btn btn-success btn-sm' %>
 <% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">BookStand</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
         <li class="nav-item"><%= link_to 'ユーザー一覧', userlist_path, method: :userlist, class: "nav-link" %></li>
         <% if logged_in? %>
           <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
           <li class="nav-item"><%= link_to '新規投稿',new_book_path, class: 'nav-link' %></li>
           
         <% else %>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
         <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Microposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>

  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<div class="row">
 <aside class="col-sm-7">
  <img class="logo" src="/assets/book.jpg" alt="booklogo">
 </aside>
  <div class="col-sm-5">
   <div class="margin"></div>
   <font size="6">新しい本に出会える場所</font>
   <br/>
   <font size="5">本に対する感想を投稿しよう</font>
  </div>
</div>
 <br>
 <p>新着投稿</p>
 <div class="boxcontiner">
  <aside class="col-sm-6">
 <% @books.first(2).each do |book| %>
      <% image = book.image %>
      <% if image.blank? %>
        <% image = "/assets/book2.jpg" %>
      <% end %>
        <img src=<%=image%> align="left" width="200" height="200">
         <%= book.user.name %>
        <img class="mr-2 rounded" src="<%= gravatar_url(book.user, { size: 50 }) %>" alt="">
        <br>
         <br>
        タイトル：<%= book.name %>
        <br>
        著者:<%= book.author %>
        <br>
        感想
        <br>
        <textarea name="kanso" rows="2" cols="40" readonly><%= book.content %></textarea>
        <br>
        <br clear="left">
        <br>
    <% end %>
    </aside>
    <aside class="col-sm-6">
    <% @books[2..3].each do |book| %>
      <% image = book.image %>
      <% if image.blank? %>
        <% image = "/assets/book2.jpg" %>
      <% end %>
        <img src=<%=image%> align="left" width="200" height="200">
         <%= book.user.name %>
        <img class="mr-2 rounded" src="<%= gravatar_url(book.user, { size: 50 }) %>" alt="">
        <br>
         <br>
        タイトル：<%= book.name %>
        <br>
        著者:<%= book.author %>
        <br>
        感想
        <br>
        <textarea readonly name="kanso" rows="2" cols="40"><%= book.content %></textarea>
        <br>
        <br clear="left">
        <br>
    <% end %>
    </aside>
    </div>
     

app/views/users/_navtab.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= books_path(@user)%>" class="nav-link <%= 'active' if current_page?(books_path(@user)) %>">Books</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">likes <span class="badge badge-secondary"><%= @count_favarites %></span></a></li>
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Mypages</a></li>
    </ul>
  </div>
</div>

app/views/users/_users.html.erb
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>

app/views/users/edit.html.erb
<%= render 'navtab',users: @user %>
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <aside class="col-sm-4">
   <div class="field">
    <%= form.label :"画像" %>
    <%= form.file_field :image %>
  </div>
  </aside>
  <aside class="col-sm-8">
  <img class="mr-2 rounded" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
  <%= @user.name %>
  
  <div class="field">
    <%= form.label :"タイトル:" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :"著者:" %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :"感想"  %>
    <%= form.text_area :content ,size: "10x5", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </aside>
</div>
<% end %>

app/views/users/followers.html.erb
<%= render 'navtab', users: @user %>
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<%= render 'navtab', users: @user %>
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
  <%= render 'navtab', users: @user %>
  <div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
       <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'navtab', users: @user %>
  <p>キーワード検索</p>
  <%= form_tag(books_path, :method => 'get' ) do %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search', :name => nil %>
  <% end %>
  <br>

    <% @books.each do |book| %>
      <% image = book.image %>
      <% if image.blank? %>
        <% image = "/assets/book.jpg" %>
      <% end %>
        <img src=<%=image%> align="left" width="400" height="300">
        <img class="mr-2 rounded" src="<%= gravatar_url(book.user, { size: 50 }) %>" alt="">
         <%= book.user.name %>
        <br>
         <%= render 'relationships/follow_button', user: book.user %>
         <br>
         <br>
        タイトル：<%= book.name %>
        <br>
        著者:<%= book.author %>
        <br>
        感想
        <br>
        <textarea name="kanso" rows="2" cols="40" readonly><%= book.content %></textarea>
        <br>
        <%= render "favorites/favorite_button" ,book: book %>
        <%= link_to "edit", edit_book_path(book_id: book.id),class: 'btn btn-success btn-sm' %>
        <%= link_to "Delete", user_path(book_id: book.id), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
        <br clear="left">
        <br>
    <% end %>
    <%= paginate @books %>

app/views/users/userlist.html.erb
<h1>ユーザー一覧</h1>
<ul class="list-unstyled">
  <div class="boxcontiner">
    <% @user.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
        </div>
      </li>
    <% end %>
    </div>
  </ul>